### ISSUE TITLE
Follow-up of the translation process

### ISSUE THREAD

**Issue by mahmudunnabikajal** [vuejs-translations/docs-bn#1]
HOME

  - [x] HOME (index.md) @mahmudunnabikajal 
 
GUIDE

  - [x]  guide/introduction.md @mahmudunnabikajal 
  - [x]  guide/quick-start.md @mahmudunnabikajal 
 
ESSENTIALS

  - [x]  guide/essentials/application.md @mahmudunnabikajal 
  - [x]  guide/essentials/template-syntax.md @mahmudunnabikajal 
  - [x]  guide/essentials/reactivity-fundamentals.md @mahmudunnabikajal 
  - [x]  guide/essentials/component-basics.md @mahmudunnabikajal 
  - [x]  guide/essentials/class-and-style.md @mahmudunnabikajal 
  - [x]  guide/essentials/computed.md @mahmudunnabikajal 
  - [x]  guide/essentials/conditional.md @mahmudunnabikajal 
  - [x]  guide/essentials/event-handling.md @mahmudunnabikajal 
  - [x]  guide/essentials/forms.md @mahmudunnabikajal 
  - [x]  guide/essentials/lifecycle.md @mahmudunnabikajal 
  - [x]  guide/essentials/list.md @mahmudunnabikajal 
  - [x]  guide/essentials/template-refs.md @mahmudunnabikajal 
  - [x]  guide/essentials/watchers.md @mahmudunnabikajal 

COMPONENTS

  - [x]  guide/components/async.md @mahmudunnabikajal 
  - [x]  guide/components/attrs.md @mahmudunnabikajal 
  - [x]  guide/components/events.md @mahmudunnabikajal 
  - [x]  guide/components/props.md @mahmudunnabikajal 
  - [x]  guide/components/provide-inject.md @mahmudunnabikajal 
  - [x]  guide/components/registration.md @mahmudunnabikajal 
  - [x]  guide/components/slots.md @mahmudunnabikajal 
  - [x]  guide/components/v-model.md @mahmudunnabikajal 

REUSABILITY
 
  - [x] guide/reusability/composables.md @mahmudunnabikajal 
  - [x]  guide/reusability/custom-directives.md @mahmudunnabikajal 
  - [x]  guide/reusability/plugins.md @mahmudunnabikajal 

BUILT-INS

  - [x]  guide/built-ins/keep-alive.md @mahmudunnabikajal
  - [x]  guide/built-ins/suspense.md @mahmudunnabikajal
  - [x]  guide/built-ins/teleport.md @mahmudunnabikajal
  - [x]  guide/built-ins/transition-group.md @mahmudunnabikajal
  - [x]  guide/built-ins/transition.md @mahmudunnabikajal

SCALING-UP

  - [x] guide/scaling-up/routing.md @mahmudunnabikajal 
  - [x]  guide/scaling-up/sfc.md @mahmudunnabikajal 
  - [x]  guide/scaling-up/ssr.md @mahmudunnabikajal 
  - [x]  guide/scaling-up/state-management.md @mahmudunnabikajal 
  - [x]  guide/scaling-up/testing.md @mahmudunnabikajal 
  - [x]  guide/scaling-up/tooling.md @mahmudunnabikajal 

BEST-PRACTICES

  - [x]  guide/best-practices/accessibility.md @mahmudunnabikajal 
  - [x]  guide/best-practices/performance.md @mahmudunnabikajal 
  - [x]  guide/best-pratices/production-deployment.md @mahmudunnabikajal 
  - [x]  guide/best-practices/security.md @mahmudunnabikajal 

TYPESCRIPT

  - [x]  guide/typescript/composition-api.md @mahmudunnabikajal 
  - [x]  guide/typescript/options-api.md @mahmudunnabikajal 
  - [x]  guide/typescript/overview.md @mahmudunnabikajal 

EXTRAS

  - [x]  guide/extras/animation.md @mahmudunnabikajal 
  - [x]  guide/extras/composition-api-faq.md @mahmudunnabikajal 
  - [x]  guide/extras/reactivity-in-depth.md @mahmudunnabikajal 
  - [x]  guide/extras/reactivity-transform.md @mahmudunnabikajal 
  - [x]  guide/extras/render-function.md @mahmudunnabikajal 
  - [x]  guide/extras/rendering-mechanism.md @mahmudunnabikajal 
  - [x]  guide/extras/ways-of-using-vue.md @mahmudunnabikajal 
  - [x]  guide/extras/web-components.md @mahmudunnabikajal 

API

  - [x]  api/application.md @mahmudunnabikajal 
  - [x]  api/built-in-components.md @mahmudunnabikajal 
  - [x]  api/built-in-directives.md @mahmudunnabikajal 
  - [x]  api/built-in-special-attributes.md @mahmudunnabikajal 
  - [x]  api/built-in-special-elements.md @mahmudunnabikajal 
  - [x]  api/component-instance.md @mahmudunnabikajal 
  - [x]  api/composition-api-dependency-injection.md @mahmudunnabikajal 
  - [x]  api/composition-api-lifecycle.md @mahmudunnabikajal 
  - [x] #17 @abuansarpatowary 
  - [x] #21 @abuansarpatowary 
  - [x] #22 @abuansarpatowary 
  - [x] #33 @abuansarpatowary 
  - [x] #34 @abuansarpatowary 
  - [x] #36 @abuansarpatowary 
  - [x] #35 @abuansarpatowary 
  - [x] #58 @abuansarpatowary
  - [x] #25 @abuansarpatowary
  - [x] #26 @abuansarpatowary
  - [x] #27 @abuansarpatowary
  - [x] #45 @abuansarpatowary
  - [x] #46 @abuansarpatowary
  - [x] #47 @abuansarpatowary
  - [x] #48 @abuansarpatowary
  - [x] #49 @abuansarpatowary
  - [x] #50 @abuansarpatowary

ECOSYSTEM
 
  - [x] ecosystem/themes.md @mahmudunnabikajal

EXAMPLES
 
  - [x] examples/index.md @mahmudunnabikajal 
  - [x]  examples/attribute-bindings @mahmudunnabikajal 
  - [x]  examples/cells @mahmudunnabikajal 
  - [x]  examples/circle-drawer @mahmudunnabikajal 
  - [x]  examples/conditionals-and-loops @mahmudunnabikajal 
  - [x]  examples/counter @mahmudunnabikajal 
  - [x]  examples/crud @mahmudunnabikajal 
  - [x]  examples/fetching-data @mahmudunnabikajal 
  - [x]  examples/flight-booker @mahmudunnabikajal 
  - [x]  examples/form-bindings @mahmudunnabikajal 
  - [x]  examples/grid @mahmudunnabikajal 
  - [x]  examples/handling-input @mahmudunnabikajal 
  - [x]  examples/hello-world @mahmudunnabikajal 
  - [x]  examples/list-transition @mahmudunnabikajal 
  - [x]  examples/markdown @mahmudunnabikajal 
  - [x]  examples/modal @mahmudunnabikajal 
  - [x]  examples/simple-component @mahmudunnabikajal 
  - [x]  examples/svg @mahmudunnabikajal 
  - [x]  examples/temperature-converter @mahmudunnabikajal 
  - [x]  examples/timer @mahmudunnabikajal 
  - [x]  examples/todomvc @mahmudunnabikajal 
  - [x]  examples/tree @mahmudunnabikajal 

ABOUT

  - [x]  about/team @mahmudunnabikajal
  - [x]  about/coc.md @mahmudunnabikajal
  - [x]  about/community-guide.md @mahmudunnabikajal
  - [x]  about/faq.md @mahmudunnabikajal
  - [x]  about/releases.md @mahmudunnabikajal
  - [x]  about/team.md @mahmudunnabikajal

SPONSOR

  - [x]  index.md @mahmudunnabikajal

STYLE-GUIDE

  - [x]  style-guide/index.md @mahmudunnabikajal
  - [x]  style-guide/rules-essential.md @mahmudunnabikajal
  - [x]  style-guide/rules-recommended.md @mahmudunnabikajal
  - [x]  style-guide/rules-strongly-recommended.md @mahmudunnabikajal
  - [x]  style-guide/rules-use-with-caution.md @mahmudunnabikajal

TRANSLATIONS

  - [x]  index.md @mahmudunnabikajal

TUTORIAL

  - [x]  tutorial/index.md @mahmudunnabikajal 
  - [x]  tutorial/step-1 @mahmudunnabikajal 
  - [x]  tutorial/step-2 @mahmudunnabikajal 
  - [x]  tutorial/step-3 @mahmudunnabikajal 
  - [x]  tutorial/step-4 @mahmudunnabikajal 
  - [x]  tutorial/step-5 @mahmudunnabikajal 
  - [x]  tutorial/step-6 @mahmudunnabikajal 
  - [x]  tutorial/step-7 @mahmudunnabikajal 
  - [x]  tutorial/step-8 @mahmudunnabikajal 
  - [x]  tutorial/step-9 @mahmudunnabikajal 
  - [x]  tutorial/step-10 @mahmudunnabikajal 
  - [x]  tutorial/step-11 @mahmudunnabikajal 
  - [x]  tutorial/step-12 @mahmudunnabikajal 
  - [x]  tutorial/step-13 @mahmudunnabikajal 
  - [x]  tutorial/step-14 @mahmudunnabikajal 
  - [x]  tutorial/step-15 @mahmudunnabikajal

**Comment by abuansarpatowary** [comment]
@mahmudunnabikajal I want to translate  api/composition-api-setup.md page now

**Comment by mahmudunnabikajal** [comment]
> @mahmudunnabikajal I want to translate api/composition-api-setup.md page now

I created a branch ```api/composition-api-setup.md``` for this page after complete translation create a pull request on this branch

**Comment by mahmudunnabikajal** [comment]
@abuansarpatowary 2 new issues and branches for each page created for you. After completing the translation create separate pull request for each page. 

Page List

- [ ] [api/custom-renderer.md](https://github.com/vuejs-translations/docs-bn/issues/21) @abuansarpatowary
- [ ] [api/general.md](https://github.com/vuejs-translations/docs-bn/issues/22) @abuansarpatowary

**Comment by mahmudunnabikajal** [comment]
A huge shoutout to all our amazing contributors! 🙌 We've successfully completed the Vuejs Bangla translation, and it's all thanks to your fantastic efforts. 📚🌟 Now, let's take the next step and ⏭️ [Recheck translation to solve issues](https://github.com/vuejs-translations/docs-bn/issues/39) together. 

🧐💪 Your support is invaluable, and we're excited to keep improving! 🚀😊"
